### PR TITLE
fixed null exception errors and miscounts

### PR DESCRIPTION
**Pull request by BadRecordLength**
Fixed null exception errors present in the console, corrected wordcount being off by one word, corrected result showing "1" when the textarea was empty after being cleared.
Live version can be viewed here:
https://badrecordlength.github.io/wordcount/

### CODE REVIEW

**Comment by jacekkopecky** [comment]
Thanks; I didn't see your PR before I made changes to fix a part of it. The code is much shorter now, but it does have the empty -> 1 bug, maybe you can extract the fix for that one please?

**Comment by BadRecordLength** [comment]
I've merged your changes and re-added the check for the textarea being empty, thanks.

**Comment by jacekkopecky** [comment]
thank you, we will probably use the ternary operator instead of the if here when we get to it

**Comment by jacekkopecky** [comment]
Shoot, I meant to merge this PR but instead clicked close, apologies for that. Anyway, we have now turned your if statement into a ternary operator and it's live. Rich also updated the CSS and added drag-n-drop, I think. Thanks for the PR – it made us do it.

**Comment by BadRecordLength** [comment]
That's OK haha, your solution is more elegant anyway, glad to at least provide the inspiration. In regards to the drag and drop functionality, this doesn't seem to work that consistently at the moment, might be worth opening a separate issue?

**Pull request closed without merging**
